spring:
  application:
    name: Photohub_Backend

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET}
    region: ${S3_REGION}
    file-name-prefix: ${S3_PREFIX}
    bucket-url: ${S3_BUCKET_URL}

server:
  tomcat:
    max-http-form-post-size: 10 0MB
